{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.taskeren.toluene",
    "module": "chart-lib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-metadata-1.0.0.jar",
          "url": "chart-lib-1.0.0.jar",
          "size": 5136,
          "sha512": "aed95ee994d2993cb3b15d1c2458e64e32ceccd343c816527e055b1bdb0868331d96e82beef821ef642fa745f6ade7af139f63adfbcb659c213c8b119c771b99",
          "sha256": "85bec433ce1ba956684dac662f8489ced0843222571d6e8cf9f778a741cff9f5",
          "sha1": "320531a4954cf628778158911b3bda17861d5c9f",
          "md5": "f20476a9e184ba4cc34986d81e7230a0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "chart-lib-kotlin-1.0.0-sources.jar",
          "url": "chart-lib-1.0.0-sources.jar",
          "size": 2959,
          "sha512": "8446ecd2ce6ce13d1f8838484cede1bbaa04824766c57e6f62dc02bfb395c485de993bc7f499d579f3cefc845cbb1388c155f86277d51232334af5cf0154c452",
          "sha256": "e57fbe8e4243017ef341c6bf7dc0ed245c714db953887015ab90e3de57bb1214",
          "sha1": "cfbeb37b667d57966c560eeba88a2743af6d7915",
          "md5": "558b357aeb9ded9368e458a5f9a454ee"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../chart-lib-js/1.0.0/chart-lib-js-1.0.0.module",
        "group": "cn.taskeren.toluene",
        "module": "chart-lib-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../chart-lib-js/1.0.0/chart-lib-js-1.0.0.module",
        "group": "cn.taskeren.toluene",
        "module": "chart-lib-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../chart-lib-js/1.0.0/chart-lib-js-1.0.0.module",
        "group": "cn.taskeren.toluene",
        "module": "chart-lib-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../chart-lib-jvm/1.0.0/chart-lib-jvm-1.0.0.module",
        "group": "cn.taskeren.toluene",
        "module": "chart-lib-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../chart-lib-jvm/1.0.0/chart-lib-jvm-1.0.0.module",
        "group": "cn.taskeren.toluene",
        "module": "chart-lib-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../chart-lib-jvm/1.0.0/chart-lib-jvm-1.0.0.module",
        "group": "cn.taskeren.toluene",
        "module": "chart-lib-jvm",
        "version": "1.0.0"
      }
    }
  ]
}
