{
  "formatVersion": "1.1",
  "component": {
    "url": "../../chart-lib/1.0.3/chart-lib-1.0.3.module",
    "group": "cn.taskeren.toluene",
    "module": "chart-lib",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-js-1.0.3.klib",
          "url": "chart-lib-js-1.0.3.klib",
          "size": 35489,
          "sha512": "64d8f53020ae478f13082204b21ad090e902ac95177bbae24deab3c2f185bdd5452fb8b6b84f9367a7dc546387b69842d7b4dac2f16cf1793b91f9c08dccc285",
          "sha256": "90c41a0616f908986ab673ea95d7ea0a54f5475fb78eecb2e8844e00a813e2f9",
          "sha1": "9a96ad2f38f2e27b6d264a79b6f8681fc5c4260e",
          "md5": "879955334942d29db678d75e3834ce38"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-js-1.0.3.klib",
          "url": "chart-lib-js-1.0.3.klib",
          "size": 35489,
          "sha512": "64d8f53020ae478f13082204b21ad090e902ac95177bbae24deab3c2f185bdd5452fb8b6b84f9367a7dc546387b69842d7b4dac2f16cf1793b91f9c08dccc285",
          "sha256": "90c41a0616f908986ab673ea95d7ea0a54f5475fb78eecb2e8844e00a813e2f9",
          "sha1": "9a96ad2f38f2e27b6d264a79b6f8681fc5c4260e",
          "md5": "879955334942d29db678d75e3834ce38"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "chart-lib-js-1.0.3-sources.jar",
          "url": "chart-lib-js-1.0.3-sources.jar",
          "size": 3671,
          "sha512": "bf5dc08a152179e294428b364fd8142cd9e78b15f0f4f99715e79ce8544eb527e5c0da74f8a399dda875c08a034393fbfc09042ed5904249e68e1ef37a4d7523",
          "sha256": "0e40b758044e7642e29277695af6f5435ddce108c6c30ffe8958d498b5825192",
          "sha1": "f505ea42377aa1c08734420ea5163ec9043337e0",
          "md5": "e295ed4779be1d8a5c0305954a7da7a6"
        }
      ]
    }
  ]
}
