{
  "formatVersion": "1.1",
  "component": {
    "url": "../../chart-lib/1.0.0/chart-lib-1.0.0.module",
    "group": "cn.taskeren.toluene",
    "module": "chart-lib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-jvm-1.0.0.jar",
          "url": "chart-lib-jvm-1.0.0.jar",
          "size": 41793,
          "sha512": "91c378609bac33b507b6a265de7416558dc5a8449335f6921397f5c3650723b09018214dde0666e7f5fa3ff1af7f92f2423e133736f3b1aa2e854b4f75646917",
          "sha256": "64aabd6d94cfaf6bf927ecc9c264f17bbda8b5d089c9e3b6ab3c061ea8593c4a",
          "sha1": "01326086a5a272649050ae98eb63598aa17f0909",
          "md5": "3a6664e6ee0afacfb49aa1e3a3aeebc3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-jvm-1.0.0.jar",
          "url": "chart-lib-jvm-1.0.0.jar",
          "size": 41793,
          "sha512": "91c378609bac33b507b6a265de7416558dc5a8449335f6921397f5c3650723b09018214dde0666e7f5fa3ff1af7f92f2423e133736f3b1aa2e854b4f75646917",
          "sha256": "64aabd6d94cfaf6bf927ecc9c264f17bbda8b5d089c9e3b6ab3c061ea8593c4a",
          "sha1": "01326086a5a272649050ae98eb63598aa17f0909",
          "md5": "3a6664e6ee0afacfb49aa1e3a3aeebc3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "chart-lib-jvm-1.0.0-sources.jar",
          "url": "chart-lib-jvm-1.0.0-sources.jar",
          "size": 3780,
          "sha512": "96bbdd004ab38805f194289ddb873df94c6fb65f067f4c7dc0e41ecc4bb2c247d4cc2c57820b5fff65ffdbc3dac937732d1377a1836a20fa3962180cd833aeba",
          "sha256": "3a95c7777fa9402a078496a68421104f8fe34401808b8c6de76bbc223271a052",
          "sha1": "f6905bb0bac1e8d314f76cd5f72f612e53655e85",
          "md5": "53f83238e5764dd7070e879584a7fecf"
        }
      ]
    }
  ]
}
