{
  "formatVersion": "1.1",
  "component": {
    "url": "../../chart-lib/1.0.1/chart-lib-1.0.1.module",
    "group": "cn.taskeren.toluene",
    "module": "chart-lib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-jvm-1.0.1.jar",
          "url": "chart-lib-jvm-1.0.1.jar",
          "size": 43422,
          "sha512": "27f0d8e014d599d2a7eb08cc9f5ab43a852a5f1907fe73b10f8eccd2ea90a422c1c43565efe28dd68b9fb9f15138f23326392f16fb041ac0f4d62e319764fc6f",
          "sha256": "1f6d19723123d1a35b903da4cd9bb5c356c4eae31474e7588b78d0fa6b5973f4",
          "sha1": "677f041273e9643da942dc87567177ff0f51c6ff",
          "md5": "60d3bdc74b551eb9b54d292aaa180774"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        }
      ],
      "files": [
        {
          "name": "chart-lib-jvm-1.0.1.jar",
          "url": "chart-lib-jvm-1.0.1.jar",
          "size": 43422,
          "sha512": "27f0d8e014d599d2a7eb08cc9f5ab43a852a5f1907fe73b10f8eccd2ea90a422c1c43565efe28dd68b9fb9f15138f23326392f16fb041ac0f4d62e319764fc6f",
          "sha256": "1f6d19723123d1a35b903da4cd9bb5c356c4eae31474e7588b78d0fa6b5973f4",
          "sha1": "677f041273e9643da942dc87567177ff0f51c6ff",
          "md5": "60d3bdc74b551eb9b54d292aaa180774"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "chart-lib-jvm-1.0.1-sources.jar",
          "url": "chart-lib-jvm-1.0.1-sources.jar",
          "size": 4432,
          "sha512": "0e37b4b7e9c2afd5617022d365e7016f4a829862714d08b560cc1d87d2212d670b6c88c5c100793ed3eb954427f2f7988af9c215d18b82224086c08c5dd10267",
          "sha256": "73b7f18906194a09cfbe23ca7ca43003e25c814ee8586119a956502d25fb4d2d",
          "sha1": "edc2f29f9f0443806242f32147c0edd104817c1b",
          "md5": "5bb28c9b14261b1d9bc2abe04646b034"
        }
      ]
    }
  ]
}
